# Generated by Django 2.0.7 on 2020-03-14 18:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=100)),
                ('address', models.TextField(max_length=100)),
                ('mobile', models.IntegerField()),
                ('career', models.TextField(max_length=30)),
                ('inter', models.TextField()),
                ('high', models.TextField()),
                ('btech', models.TextField()),
                ('image', models.ImageField(blank=True, upload_to='images/')),
                ('work', models.TextField(max_length=100)),
                ('title1', models.CharField(max_length=30)),
                ('description1', models.TextField()),
                ('duartion1', models.TextField()),
                ('role1', models.TextField()),
                ('teamsize1', models.IntegerField(blank=True)),
                ('title2', models.CharField(blank=True, max_length=30)),
                ('description2', models.TextField(blank=True)),
                ('duartion2', models.TextField(blank=True)),
                ('role2', models.TextField(blank=True)),
                ('teamsize2', models.IntegerField(blank=True)),
                ('field', models.TextField(max_length=20)),
                ('skill1', models.TextField()),
                ('skill2', models.TextField(blank=True)),
                ('skill3', models.TextField(blank=True)),
                ('achievement1', models.TextField(blank=True)),
                ('achievement2', models.TextField(blank=True)),
                ('achievement3', models.TextField(blank=True)),
                ('achievement4', models.TextField(blank=True)),
                ('achievement5', models.TextField(blank=True)),
                ('hunter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
