# Generated by Django 2.0.7 on 2020-03-14 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='title2',
            field=models.CharField(default=False, max_length=30),
        ),
    ]
