# Generated by Django 2.0.7 on 2020-03-14 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20200314_2359'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='skill3',
        ),
    ]
