# Generated by Django 2.0.7 on 2020-03-14 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_remove_product_skill3'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='skill3',
            field=models.TextField(blank=True),
        ),
    ]
