# Generated by Django 2.0.7 on 2020-03-15 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20200315_1546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='career',
            field=models.TextField(choices=[('OBJECTIVE1', 'To secure a position with a stable and profitable organization,where i can be a member of a team and utilize my bussiness experience to the fullest'), ('OBJECTIVE2', 'To obtain a challenging position in a high quality engineering environment where my resourceful experience and academic skills will add value to organizational operations')], max_length=30),
        ),
    ]
