# Generated by Django 3.0.4 on 2020-03-21 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_auto_20200315_2336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='career',
            field=models.TextField(choices=[('To secure a position with a stable and profitable organization,where i can be a member of a team and utilize my bussiness experience to the fullest', 'OBJECTIVE1'), ('To obtain a challenging position in a high quality engineering environment where my resourceful experience and academic skills will add value to organizational operations', 'OBJECTIVE2')], max_length=200),
        ),
    ]
