# Generated by Django 3.0.4 on 2020-03-21 09:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0009_auto_20200321_1139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='achievement1',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='product',
            name='achievement2',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='product',
            name='achievement3',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='product',
            name='achievement4',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='product',
            name='achievement5',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='product',
            name='address',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='btech',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='product',
            name='description1',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='product',
            name='description2',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='product',
            name='duartion1',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='product',
            name='duartion2',
            field=models.TextField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='product',
            name='field',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='product',
            name='high',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='product',
            name='hunter',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='product',
            name='inter',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='product',
            name='role1',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='product',
            name='role2',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='product',
            name='skill1',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='product',
            name='skill2',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='product',
            name='skill3',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='product',
            name='title1',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='product',
            name='work',
            field=models.CharField(max_length=100),
        ),
    ]
